blank_issues_enabled: true
contact_links:
    - name: Feature Requests
      url: https://github.com/Hans-4/home-energy-manager-sax-power/discussions
      about: Discuss ideas for new features or changes
